CREATE TABLE customers (
    id BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
    cnpj VARCHAR(14) UNIQUE NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    token VARCHAR(6),
    token_expiration TIMESTAMP
);